yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_posts'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(verbose_name='title', max_length=200)
    slug = models.SlugField(verbose_name='slug', unique=True)
    description = models.TextField(verbose_name='description')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='content')
    pub_date = models.DateTimeField(verbose_name='date', auto_now_add=True)
    author = models.ForeignKey(User,
                               verbose_name='author',
                               on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey(Group,
                              verbose_name='group',
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts')

    class Meta:
        ordering = ['-pub_date']

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


POST_QUANTITY = 10


def index(request):
    posts = Post.objects.all()[:POST_QUANTITY]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:POST_QUANTITY]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
        <div class="container">
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
        </div>

    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- templates/ice_cream/ice_cream_list.html -->
<!DOCTYPE html>
<html lang="ru">
  <head>
  </head>
  <body>
    <header>

    </header>
    <main>

    </main>
   <footer class="page-footer font-small blue border-top">
      <div class="footer-copyright text-center py-3">© 2020 Copyright
        <p><span style="color:red">Ya</span>tube</p>
      </div>

    </footer>
  </body>
</html>

yatube/templates/includes/header.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
  <head>

  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <img class="py-5" src="{% static 'img/logo.png' %}" href="{% url 'posts:main_posts' %}">
        <div class="container">
          <a class="navbar-brand" href="index.html"><span style="color:red; padding-left:1px">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>
    <main>

    </main>
    <footer>
    </footer>
  </body>
</html>

yatube/templates/posts/group_list.html
  {% extends 'base.html' %}
    {% block title %}
    <title>Записи сообщества {{ post.group }}</title>
    {% endblock %}
    {% block content %}
    <h1>Лев Толстой – зеркало русской революции.</h1>
    {% for post in posts %}
      <ul>
        <li>Автор: {{ post.author.get_full_name }}</li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y"}}</li>
      </ul>
      <p>{{ post.text }}</p>
      {% if not forloop.last %}<hr>{% endif %}

    {% endfor %}
    {% endblock %}

yatube/templates/posts/index.html
  {% extends 'base.html' %}
    {% block title %}
    <title>Последние обновления на сайте.</title>
    {% endblock %}
    {% block content %}
    <h1>Последние обновления на сайте.</h1>
    {% for post in posts %}
    <div>
    <ul>
        <li>Автор: {{ post.author.get_full_name }}</li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y"}}</li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
   {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  </>
  {% endfor %}
  {% endblock %}